"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.driverRouter = void 0;
const express_1 = require("express");
// import {Request, Response} from "express";
// import {driversDb} from "../db/mock-data";
// import {Driver, DriverStatus} from "../drivers/driver-types";
// import {driverInputDtoValidation} from "../drivers/driver-body-validation";
// import {ValidationError} from "../core/validation-error";
// import {HttpStatus} from "../core/http-statuses";
const router_descriptions_1 = require("./router.descriptions");
const input_id_validation_middleware_1 = require("../validation/input-id-validation_middleware");
const error_management_validation_middleware_1 = require("../validation/error-management-validation_middleware");
const driver_dto_validation_middleware_1 = require("../validation/driver-dto-validation_middleware");
const base64_auth_guard_middleware_1 = require("../validation/base64-auth-guard_middleware");
exports.driverRouter = (0, express_1.Router)();
exports.driverRouter.get("/", router_descriptions_1.getDriversList);
exports.driverRouter.get("/:id", input_id_validation_middleware_1.inputIdValidation, error_management_validation_middleware_1.inputValidationResultMiddleware, router_descriptions_1.getDriverById);
exports.driverRouter.post("/", base64_auth_guard_middleware_1.superAdminGuardMiddleware, driver_dto_validation_middleware_1.driverInputDtoValidation, error_management_validation_middleware_1.inputValidationResultMiddleware, router_descriptions_1.createNewDriver);
